// ============================================================
//  MAP QUIZ — Base de datos de países
// ============================================================

const PAISES = [
  // ── AMÉRICA DEL NORTE ────────────────────────────────────
  { id:  1, nombre: "México",               code: "mx", capital: "Ciudad de México",    region: "america_norte", poblacion: 128932753 },
  { id:  2, nombre: "Canadá",               code: "ca", capital: "Ottawa",              region: "america_norte", poblacion: 38005238  },
  { id:  3, nombre: "Estados Unidos",       code: "us", capital: "Washington D.C.",     region: "america_norte", poblacion: 331002651 },
  { id:  4, nombre: "Cuba",                 code: "cu", capital: "La Habana",           region: "america_norte", poblacion: 11326616  },
  { id:  5, nombre: "Guatemala",            code: "gt", capital: "Ciudad de Guatemala", region: "america_norte", poblacion: 17109746  },
  { id:  6, nombre: "Honduras",             code: "hn", capital: "Tegucigalpa",         region: "america_norte", poblacion: 9904607   },
  { id:  7, nombre: "El Salvador",          code: "sv", capital: "San Salvador",        region: "america_norte", poblacion: 6486205   },
  { id:  8, nombre: "Nicaragua",            code: "ni", capital: "Managua",             region: "america_norte", poblacion: 6624554   },
  { id:  9, nombre: "Costa Rica",           code: "cr", capital: "San José",            region: "america_norte", poblacion: 5094118   },
  { id: 10, nombre: "Panamá",               code: "pa", capital: "Ciudad de Panamá",    region: "america_norte", poblacion: 4351267   },
  { id: 11, nombre: "Jamaica",              code: "jm", capital: "Kingston",            region: "america_norte", poblacion: 2961167   },
  { id: 12, nombre: "República Dominicana", code: "do", capital: "Santo Domingo",       region: "america_norte", poblacion: 10847910  },
  { id: 13, nombre: "Haití",                code: "ht", capital: "Puerto Príncipe",     region: "america_norte", poblacion: 11402528  },
  { id: 14, nombre: "Trinidad y Tobago",    code: "tt", capital: "Puerto España",       region: "america_norte", poblacion: 1399488   },
  { id: 15, nombre: "Bahamas",              code: "bs", capital: "Nasáu",               region: "america_norte", poblacion: 393244    },
  { id: 16, nombre: "Belice",               code: "bz", capital: "Belmopán",            region: "america_norte", poblacion: 397628    },

  // ── AMÉRICA DEL SUR ──────────────────────────────────────
  { id: 17, nombre: "Brasil",               code: "br", capital: "Brasilia",            region: "america_sur",   poblacion: 212559417 },
  { id: 18, nombre: "Colombia",             code: "co", capital: "Bogotá",              region: "america_sur",   poblacion: 50882891  },
  { id: 19, nombre: "Argentina",            code: "ar", capital: "Buenos Aires",        region: "america_sur",   poblacion: 45195774  },
  { id: 20, nombre: "Perú",                 code: "pe", capital: "Lima",                region: "america_sur",   poblacion: 32971854  },
  { id: 21, nombre: "Venezuela",            code: "ve", capital: "Caracas",             region: "america_sur",   poblacion: 28435943  },
  { id: 22, nombre: "Chile",                code: "cl", capital: "Santiago",            region: "america_sur",   poblacion: 19116201  },
  { id: 23, nombre: "Ecuador",              code: "ec", capital: "Quito",               region: "america_sur",   poblacion: 17643054  },
  { id: 24, nombre: "Bolivia",              code: "bo", capital: "Sucre",               region: "america_sur",   poblacion: 11673021  },
  { id: 25, nombre: "Paraguay",             code: "py", capital: "Asunción",            region: "america_sur",   poblacion: 7132538   },
  { id: 26, nombre: "Uruguay",              code: "uy", capital: "Montevideo",          region: "america_sur",   poblacion: 3473730   },
  { id: 27, nombre: "Guyana",               code: "gy", capital: "Georgetown",          region: "america_sur",   poblacion: 786552    },
  { id: 28, nombre: "Surinam",              code: "sr", capital: "Paramaribo",          region: "america_sur",   poblacion: 586632    },

  // ── EUROPA ───────────────────────────────────────────────
  { id: 29, nombre: "Francia",              code: "fr", capital: "París",               region: "europa",        poblacion: 65273511  },
  { id: 30, nombre: "Alemania",             code: "de", capital: "Berlín",              region: "europa",        poblacion: 83783942  },
  { id: 31, nombre: "España",               code: "es", capital: "Madrid",              region: "europa",        poblacion: 46754778  },
  { id: 32, nombre: "Italia",               code: "it", capital: "Roma",                region: "europa",        poblacion: 60461826  },
  { id: 33, nombre: "Reino Unido",          code: "gb", capital: "Londres",             region: "europa",        poblacion: 67886011  },
  { id: 34, nombre: "Portugal",             code: "pt", capital: "Lisboa",              region: "europa",        poblacion: 10196709  },
  { id: 35, nombre: "Países Bajos",         code: "nl", capital: "Ámsterdam",           region: "europa",        poblacion: 17134872  },
  { id: 36, nombre: "Bélgica",              code: "be", capital: "Bruselas",            region: "europa",        poblacion: 11589623  },
  { id: 37, nombre: "Suiza",                code: "ch", capital: "Berna",               region: "europa",        poblacion: 8654622   },
  { id: 38, nombre: "Austria",              code: "at", capital: "Viena",               region: "europa",        poblacion: 9006398   },
  { id: 39, nombre: "Polonia",              code: "pl", capital: "Varsovia",            region: "europa",        poblacion: 37846611  },
  { id: 40, nombre: "Suecia",               code: "se", capital: "Estocolmo",           region: "europa",        poblacion: 10099265  },
  { id: 41, nombre: "Noruega",              code: "no", capital: "Oslo",                region: "europa",        poblacion: 5421241   },
  { id: 42, nombre: "Dinamarca",            code: "dk", capital: "Copenhague",          region: "europa",        poblacion: 5792202   },
  { id: 43, nombre: "Finlandia",            code: "fi", capital: "Helsinki",            region: "europa",        poblacion: 5540720   },
  { id: 44, nombre: "Grecia",               code: "gr", capital: "Atenas",              region: "europa",        poblacion: 10715549  },
  { id: 45, nombre: "Turquía",              code: "tr", capital: "Ankara",              region: "europa",        poblacion: 84339067  },
  { id: 46, nombre: "Rusia",                code: "ru", capital: "Moscú",               region: "europa",        poblacion: 145934462 },
  { id: 47, nombre: "Ucrania",              code: "ua", capital: "Kiev",                region: "europa",        poblacion: 43733762  },
  { id: 48, nombre: "República Checa",      code: "cz", capital: "Praga",               region: "europa",        poblacion: 10708981  },
  { id: 49, nombre: "Rumania",              code: "ro", capital: "Bucarest",            region: "europa",        poblacion: 19237691  },
  { id: 50, nombre: "Hungría",              code: "hu", capital: "Budapest",            region: "europa",        poblacion: 9660351   },
  { id: 51, nombre: "Serbia",               code: "rs", capital: "Belgrado",            region: "europa",        poblacion: 8737371   },
  { id: 52, nombre: "Croacia",              code: "hr", capital: "Zagreb",              region: "europa",        poblacion: 4105267   },
  { id: 53, nombre: "Irlanda",              code: "ie", capital: "Dublín",              region: "europa",        poblacion: 4937786   },
  { id: 54, nombre: "Bulgaria",             code: "bg", capital: "Sofía",               region: "europa",        poblacion: 6948445   },
  { id: 55, nombre: "Eslovaquia",           code: "sk", capital: "Bratislava",          region: "europa",        poblacion: 5459642   },
  { id: 56, nombre: "Albania",              code: "al", capital: "Tirana",              region: "europa",        poblacion: 2877797   },
  { id: 57, nombre: "Eslovenia",            code: "si", capital: "Liubliana",           region: "europa",        poblacion: 2078938   },
  { id: 58, nombre: "Lituania",             code: "lt", capital: "Vilna",               region: "europa",        poblacion: 2722289   },
  { id: 59, nombre: "Letonia",              code: "lv", capital: "Riga",                region: "europa",        poblacion: 1886198   },
  { id: 60, nombre: "Estonia",              code: "ee", capital: "Tallin",              region: "europa",        poblacion: 1326535   },
  { id: 61, nombre: "Macedonia del Norte",  code: "mk", capital: "Skopie",              region: "europa",        poblacion: 2083459   },
  { id: 62, nombre: "Bosnia y Herzegovina", code: "ba", capital: "Sarajevo",            region: "europa",        poblacion: 3280819   },
  { id: 63, nombre: "Luxemburgo",           code: "lu", capital: "Luxemburgo",          region: "europa",        poblacion: 625978    },
  { id: 64, nombre: "Malta",                code: "mt", capital: "La Valeta",           region: "europa",        poblacion: 441543    },
  { id: 65, nombre: "Islandia",             code: "is", capital: "Reikiavik",           region: "europa",        poblacion: 341243    },

  // ── ASIA ─────────────────────────────────────────────────
  { id: 66, nombre: "China",                     code: "cn", capital: "Pekín",               region: "asia", poblacion: 1439323776 },
  { id: 67, nombre: "India",                     code: "in", capital: "Nueva Delhi",          region: "asia", poblacion: 1380004385 },
  { id: 68, nombre: "Japón",                     code: "jp", capital: "Tokio",               region: "asia", poblacion: 126476461  },
  { id: 69, nombre: "Corea del Sur",             code: "kr", capital: "Seúl",               region: "asia", poblacion: 51269185   },
  { id: 70, nombre: "Indonesia",                 code: "id", capital: "Yakarta",             region: "asia", poblacion: 273523615  },
  { id: 71, nombre: "Tailandia",                 code: "th", capital: "Bangkok",             region: "asia", poblacion: 69799978   },
  { id: 72, nombre: "Vietnam",                   code: "vn", capital: "Hanói",               region: "asia", poblacion: 97338579   },
  { id: 73, nombre: "Filipinas",                 code: "ph", capital: "Manila",              region: "asia", poblacion: 109581078  },
  { id: 74, nombre: "Malasia",                   code: "my", capital: "Kuala Lumpur",        region: "asia", poblacion: 32365999   },
  { id: 75, nombre: "Arabia Saudita",            code: "sa", capital: "Riad",                region: "asia", poblacion: 34813871   },
  { id: 76, nombre: "Irak",                      code: "iq", capital: "Bagdad",              region: "asia", poblacion: 40222493   },
  { id: 77, nombre: "Irán",                      code: "ir", capital: "Teherán",             region: "asia", poblacion: 83992949   },
  { id: 78, nombre: "Israel",                    code: "il", capital: "Jerusalén",           region: "asia", poblacion: 8655535    },
  { id: 79, nombre: "Emiratos Árabes Unidos",    code: "ae", capital: "Abu Dabi",            region: "asia", poblacion: 9890402    },
  { id: 80, nombre: "Pakistán",                  code: "pk", capital: "Islamabad",           region: "asia", poblacion: 220892340  },
  { id: 81, nombre: "Bangladesh",                code: "bd", capital: "Daca",                region: "asia", poblacion: 164689383  },
  { id: 82, nombre: "Nepal",                     code: "np", capital: "Katmandú",            region: "asia", poblacion: 29136808   },
  { id: 83, nombre: "Sri Lanka",                 code: "lk", capital: "Colombo",             region: "asia", poblacion: 21413249   },
  { id: 84, nombre: "Singapur",                  code: "sg", capital: "Singapur",            region: "asia", poblacion: 5850342    },
  { id: 85, nombre: "Mongolia",                  code: "mn", capital: "Ulán Bator",          region: "asia", poblacion: 3278290    },
  { id: 86, nombre: "Kazajistán",                code: "kz", capital: "Astana",              region: "asia", poblacion: 18776707   },
  { id: 87, nombre: "Afganistán",                code: "af", capital: "Kabul",               region: "asia", poblacion: 38928346   },
  { id: 88, nombre: "Siria",                     code: "sy", capital: "Damasco",             region: "asia", poblacion: 17500658   },
  { id: 89, nombre: "Yemen",                     code: "ye", capital: "Saná",               region: "asia", poblacion: 29825964   },
  { id: 90, nombre: "Jordania",                  code: "jo", capital: "Amán",               region: "asia", poblacion: 10203134   },
  { id: 91, nombre: "Myanmar",                   code: "mm", capital: "Naipyidó",           region: "asia", poblacion: 54409800   },
  { id: 92, nombre: "Corea del Norte",           code: "kp", capital: "Pionyang",           region: "asia", poblacion: 25778816   },
  { id: 93, nombre: "Camboya",                   code: "kh", capital: "Nom Pen",            region: "asia", poblacion: 16718965   },
  { id: 94, nombre: "Uzbekistán",                code: "uz", capital: "Taskent",            region: "asia", poblacion: 33469203   },
  { id: 95, nombre: "Azerbaiyán",                code: "az", capital: "Bakú",               region: "asia", poblacion: 10139177   },
  { id: 96, nombre: "Georgia",                   code: "ge", capital: "Tiflis",             region: "asia", poblacion: 3989167    },
  { id: 97, nombre: "Armenia",                   code: "am", capital: "Ereván",             region: "asia", poblacion: 2963243    },
  { id: 98, nombre: "Qatar",                     code: "qa", capital: "Doha",               region: "asia", poblacion: 2881053    },
  { id: 99, nombre: "Kuwait",                    code: "kw", capital: "Ciudad de Kuwait",   region: "asia", poblacion: 4270571    },
  { id:100, nombre: "Omán",                      code: "om", capital: "Mascate",            region: "asia", poblacion: 4974986    },

  // ── ÁFRICA ───────────────────────────────────────────────
  { id:101, nombre: "Nigeria",                         code: "ng", capital: "Abuya",         region: "africa", poblacion: 206139589 },
  { id:102, nombre: "Etiopía",                         code: "et", capital: "Adís Abeba",    region: "africa", poblacion: 114963588 },
  { id:103, nombre: "Egipto",                          code: "eg", capital: "El Cairo",      region: "africa", poblacion: 102334404 },
  { id:104, nombre: "Rep. Dem. del Congo",             code: "cd", capital: "Kinshasa",      region: "africa", poblacion: 89561403  },
  { id:105, nombre: "Tanzania",                        code: "tz", capital: "Dodoma",         region: "africa", poblacion: 59734218  },
  { id:106, nombre: "Kenia",                           code: "ke", capital: "Nairobi",        region: "africa", poblacion: 53771296  },
  { id:107, nombre: "Sudáfrica",                       code: "za", capital: "Pretoria",       region: "africa", poblacion: 59308690  },
  { id:108, nombre: "Argelia",                         code: "dz", capital: "Argel",          region: "africa", poblacion: 43851044  },
  { id:109, nombre: "Marruecos",                       code: "ma", capital: "Rabat",          region: "africa", poblacion: 36910560  },
  { id:110, nombre: "Mozambique",                      code: "mz", capital: "Maputo",          region: "africa", poblacion: 31255435  },
  { id:111, nombre: "Ghana",                           code: "gh", capital: "Acra",           region: "africa", poblacion: 31072940  },
  { id:112, nombre: "Costa de Marfil",                 code: "ci", capital: "Yamusukro",      region: "africa", poblacion: 26378274  },
  { id:113, nombre: "Camerún",                         code: "cm", capital: "Yaundé",         region: "africa", poblacion: 26545863  },
  { id:114, nombre: "Senegal",                         code: "sn", capital: "Dakar",          region: "africa", poblacion: 16743927  },
  { id:115, nombre: "Zimbabue",                        code: "zw", capital: "Harare",         region: "africa", poblacion: 14862924  },
  { id:116, nombre: "Túnez",                           code: "tn", capital: "Túnez",          region: "africa", poblacion: 11818619  },
  { id:117, nombre: "Libia",                           code: "ly", capital: "Trípoli",        region: "africa", poblacion: 6871292   },
  { id:118, nombre: "Somalia",                         code: "so", capital: "Mogadiscio",     region: "africa", poblacion: 15893222  },
  { id:119, nombre: "Sudán",                           code: "sd", capital: "Jartum",         region: "africa", poblacion: 43849260  },
  { id:120, nombre: "Uganda",                          code: "ug", capital: "Kampala",        region: "africa", poblacion: 45741007  },
  { id:121, nombre: "Angola",                          code: "ao", capital: "Luanda",         region: "africa", poblacion: 32866272  },
  { id:122, nombre: "Zambia",                          code: "zm", capital: "Lusaka",         region: "africa", poblacion: 18383955  },
  { id:123, nombre: "Ruanda",                          code: "rw", capital: "Kigali",         region: "africa", poblacion: 12952218  },
  { id:124, nombre: "Madagascar",                      code: "mg", capital: "Antananarivo",   region: "africa", poblacion: 27691018  },
  { id:125, nombre: "Botsuana",                        code: "bw", capital: "Gaborone",       region: "africa", poblacion: 2351627   },
  { id:126, nombre: "Namibia",                         code: "na", capital: "Windhoek",       region: "africa", poblacion: 2540905   },
  { id:127, nombre: "Mauritania",                      code: "mr", capital: "Nuakchot",       region: "africa", poblacion: 4649658   },
  { id:128, nombre: "Gabón",                           code: "ga", capital: "Libreville",     region: "africa", poblacion: 2225734   },

  // ── OCEANÍA ──────────────────────────────────────────────
  { id:129, nombre: "Australia",          code: "au", capital: "Canberra",       region: "oceania", poblacion: 25499884 },
  { id:130, nombre: "Nueva Zelanda",      code: "nz", capital: "Wellington",     region: "oceania", poblacion: 4822233  },
  { id:131, nombre: "Papúa Nueva Guinea", code: "pg", capital: "Port Moresby",   region: "oceania", poblacion: 8947024  },
  { id:132, nombre: "Fiyi",               code: "fj", capital: "Suva",           region: "oceania", poblacion: 896445   },
  { id:133, nombre: "Vanuatu",            code: "vu", capital: "Port Vila",      region: "oceania", poblacion: 307145   },
  { id:134, nombre: "Samoa",              code: "ws", capital: "Apia",           region: "oceania", poblacion: 198414   },

  // ── AMÉRICA DEL NORTE (adicionales) ─────────────────────────
  { id:135, nombre: "Barbados",               code: "bb", capital: "Bridgetown",       region: "america_norte", poblacion: 287375   },
  { id:136, nombre: "San Vicente y las Granadinas", code: "vc", capital: "Kingstown", region: "america_norte", poblacion: 110940   },
  { id:137, nombre: "Santa Lucía",            code: "lc", capital: "Castries",          region: "america_norte", poblacion: 183627   },
  { id:138, nombre: "Granada",                code: "gd", capital: "Saint George's",    region: "america_norte", poblacion: 112523   },
  { id:139, nombre: "Antigua y Barbuda",      code: "ag", capital: "Saint John's",      region: "america_norte", poblacion: 97929    },
  { id:140, nombre: "Dominica",               code: "dm", capital: "Roseau",            region: "america_norte", poblacion: 71986    },
  { id:141, nombre: "San Cristóbal y Nieves", code: "kn", capital: "Basseterre",        region: "america_norte", poblacion: 53199    },

  // ── EUROPA (adicionales) ──────────────────────────────────────
  { id:142, nombre: "Montenegro",             code: "me", capital: "Podgorica",         region: "europa",        poblacion: 628066   },
  { id:143, nombre: "Andorra",                code: "ad", capital: "Andorra la Vella",  region: "europa",        poblacion: 77265    },
  { id:144, nombre: "Liechtenstein",          code: "li", capital: "Vaduz",             region: "europa",        poblacion: 38128    },
  { id:145, nombre: "Mónaco",                 code: "mc", capital: "Mónaco",            region: "europa",        poblacion: 39242    },
  { id:146, nombre: "San Marino",             code: "sm", capital: "San Marino",        region: "europa",        poblacion: 33931    },
  { id:147, nombre: "Kosovo",                 code: "xk", capital: "Pristina",          region: "europa",        poblacion: 1775378  },
  { id:148, nombre: "Moldova",                code: "md", capital: "Chisináu",          region: "europa",        poblacion: 2657637  },
  { id:149, nombre: "Bielorrusia",            code: "by", capital: "Minsk",             region: "europa",        poblacion: 9449323  },
  { id:150, nombre: "Chipre",                 code: "cy", capital: "Nicosia",           region: "europa",        poblacion: 1207359  },

  // ── ASIA (adicionales) ────────────────────────────────────────
  { id:151, nombre: "Laos",                   code: "la", capital: "Vientián",          region: "asia",          poblacion: 7275560  },
  { id:152, nombre: "Timor Oriental",         code: "tl", capital: "Dili",              region: "asia",          poblacion: 1318445  },
  { id:153, nombre: "Brunéi",                 code: "bn", capital: "Bandar Seri Begawan",region: "asia",         poblacion: 437479   },
  { id:154, nombre: "Maldivas",               code: "mv", capital: "Malé",              region: "asia",          poblacion: 540985   },
  { id:155, nombre: "Bután",                  code: "bt", capital: "Timbu",             region: "asia",          poblacion: 771608   },
  { id:156, nombre: "Kirguistán",             code: "kg", capital: "Biskek",            region: "asia",          poblacion: 6524195  },
  { id:157, nombre: "Tayikistán",             code: "tj", capital: "Dusambé",           region: "asia",          poblacion: 9537645  },
  { id:158, nombre: "Turkmenistán",           code: "tm", capital: "Asjabad",           region: "asia",          poblacion: 6031200  },
  { id:159, nombre: "Líbano",                 code: "lb", capital: "Beirut",            region: "asia",          poblacion: 6825445  },
  { id:160, nombre: "Palestina",              code: "ps", capital: "Ramala",            region: "asia",          poblacion: 5101414  },
  { id:161, nombre: "Bahréin",                code: "bh", capital: "Manama",            region: "asia",          poblacion: 1701575  },

  // ── ÁFRICA (adicionales) ──────────────────────────────────────
  { id:162, nombre: "Malí",                   code: "ml", capital: "Bamako",            region: "africa",        poblacion: 20250833 },
  { id:163, nombre: "Burkina Faso",           code: "bf", capital: "Uagadugú",          region: "africa",        poblacion: 20903273 },
  { id:164, nombre: "Níger",                  code: "ne", capital: "Niamey",            region: "africa",        poblacion: 24206636 },
  { id:165, nombre: "Chad",                   code: "td", capital: "Yamena",            region: "africa",        poblacion: 16425864 },
  { id:166, nombre: "Sudán del Sur",          code: "ss", capital: "Yuba",              region: "africa",        poblacion: 11193725 },
  { id:167, nombre: "Rep. Centroafricana",    code: "cf", capital: "Bangui",            region: "africa",        poblacion: 4829767  },
  { id:168, nombre: "Rep. del Congo",         code: "cg", capital: "Brazzaville",       region: "africa",        poblacion: 5518092  },
  { id:169, nombre: "Benín",                  code: "bj", capital: "Porto Novo",        region: "africa",        poblacion: 12123200 },
  { id:170, nombre: "Togo",                   code: "tg", capital: "Lomé",              region: "africa",        poblacion: 8278724  },
  { id:171, nombre: "Guinea",                 code: "gn", capital: "Conakri",           region: "africa",        poblacion: 13132795 },
  { id:172, nombre: "Sierra Leona",           code: "sl", capital: "Freetown",          region: "africa",        poblacion: 7976985  },
  { id:173, nombre: "Liberia",                code: "lr", capital: "Monrovia",          region: "africa",        poblacion: 5057681  },
  { id:174, nombre: "Guinea-Bisáu",           code: "gw", capital: "Bisáu",             region: "africa",        poblacion: 1968001  },
  { id:175, nombre: "Gambia",                 code: "gm", capital: "Banjul",            region: "africa",        poblacion: 2416668  },
  { id:176, nombre: "Guinea Ecuatorial",      code: "gq", capital: "Malabo",            region: "africa",        poblacion: 1402985  },
  { id:177, nombre: "Eritrea",                code: "er", capital: "Asmara",            region: "africa",        poblacion: 3546421  },
  { id:178, nombre: "Yibuti",                 code: "dj", capital: "Yibuti",            region: "africa",        poblacion: 988000   },
  { id:179, nombre: "Malaui",                 code: "mw", capital: "Lilongüe",          region: "africa",        poblacion: 19129952 },
  { id:180, nombre: "Suazilandia",            code: "sz", capital: "Mbabane",           region: "africa",        poblacion: 1160164  },
  { id:181, nombre: "Lesoto",                 code: "ls", capital: "Maseru",            region: "africa",        poblacion: 2142249  },
  { id:182, nombre: "Burundi",                code: "bi", capital: "Gitega",            region: "africa",        poblacion: 11890784 },
  { id:183, nombre: "Cabo Verde",             code: "cv", capital: "Praia",             region: "africa",        poblacion: 555987   },
  { id:184, nombre: "Santo Tomé y Príncipe",  code: "st", capital: "Santo Tomé",        region: "africa",        poblacion: 219159   },
  { id:185, nombre: "Comoras",                code: "km", capital: "Moroni",            region: "africa",        poblacion: 869601   },
  { id:186, nombre: "Seychelles",             code: "sc", capital: "Victoria",          region: "africa",        poblacion: 98347    },
  { id:187, nombre: "Mauricio",               code: "mu", capital: "Port Louis",        region: "africa",        poblacion: 1271768  },

  // ── OCEANÍA (adicionales) ─────────────────────────────────────
  { id:188, nombre: "Salomón",                code: "sb", capital: "Honiara",           region: "oceania",       poblacion: 686884   },
  { id:189, nombre: "Kiribati",               code: "ki", capital: "Tarawa del Sur",    region: "oceania",       poblacion: 119449   },
  { id:190, nombre: "Micronesia",             code: "fm", capital: "Palikir",           region: "oceania",       poblacion: 115023   },
  { id:191, nombre: "Tonga",                  code: "to", capital: "Nukualofa",         region: "oceania",       poblacion: 105695   },
  { id:192, nombre: "Palaos",                 code: "pw", capital: "Ngerulmud",         region: "oceania",       poblacion: 18094    },
  { id:193, nombre: "Tuvalu",                 code: "tv", capital: "Funafuti",          region: "oceania",       poblacion: 11792    },
  { id:194, nombre: "Nauru",                  code: "nr", capital: "Yaren",             region: "oceania",       poblacion: 10824    },
  { id:195, nombre: "Marshall",               code: "mh", capital: "Majuro",            region: "oceania",       poblacion: 59190    },

];

// ── VECINOS POR PAÍS (para el modo Wordle) ───────────────────
// Mapeado por nombre de país → array de nombres de vecinos
const VECINOS = {
  "México":               ["Estados Unidos", "Guatemala", "Belice"],
  "Canadá":               ["Estados Unidos"],
  "Estados Unidos":       ["Canadá", "México"],
  "Cuba":                 [],
  "Guatemala":            ["México", "Belice", "Honduras", "El Salvador"],
  "Honduras":             ["Guatemala", "El Salvador", "Nicaragua"],
  "El Salvador":          ["Guatemala", "Honduras"],
  "Nicaragua":            ["Honduras", "Costa Rica"],
  "Costa Rica":           ["Nicaragua", "Panamá"],
  "Panamá":               ["Costa Rica", "Colombia"],
  "Jamaica":              [],
  "República Dominicana": ["Haití"],
  "Haití":                ["República Dominicana"],
  "Trinidad y Tobago":    [],
  "Bahamas":              [],
  "Belice":               ["México", "Guatemala"],
  "Brasil":               ["Colombia", "Venezuela", "Guyana", "Surinam", "Bolivia", "Perú", "Argentina", "Paraguay", "Uruguay"],
  "Colombia":             ["Panamá", "Venezuela", "Brasil", "Perú", "Ecuador"],
  "Argentina":            ["Chile", "Bolivia", "Paraguay", "Brasil", "Uruguay"],
  "Perú":                 ["Ecuador", "Colombia", "Brasil", "Bolivia", "Chile"],
  "Venezuela":            ["Colombia", "Brasil", "Guyana"],
  "Chile":                ["Perú", "Bolivia", "Argentina"],
  "Ecuador":              ["Colombia", "Perú"],
  "Bolivia":              ["Perú", "Brasil", "Paraguay", "Argentina", "Chile"],
  "Paraguay":             ["Bolivia", "Brasil", "Argentina"],
  "Uruguay":              ["Brasil", "Argentina"],
  "Guyana":               ["Venezuela", "Brasil", "Surinam"],
  "Surinam":              ["Guyana", "Brasil"],
  "Francia":              ["Bélgica", "Luxemburgo", "Alemania", "Suiza", "Italia", "España", "Andorra", "Mónaco"],
  "Alemania":             ["Dinamarca", "Polonia", "República Checa", "Austria", "Suiza", "Francia", "Luxemburgo", "Bélgica", "Países Bajos"],
  "España":               ["Portugal", "Francia", "Andorra"],
  "Italia":               ["Francia", "Suiza", "Austria", "Eslovenia"],
  "Reino Unido":          ["Irlanda"],
  "Portugal":             ["España"],
  "Países Bajos":         ["Alemania", "Bélgica"],
  "Bélgica":              ["Francia", "Luxemburgo", "Alemania", "Países Bajos"],
  "Suiza":                ["Francia", "Alemania", "Austria", "Liechtenstein", "Italia"],
  "Austria":              ["Alemania", "República Checa", "Eslovaquia", "Hungría", "Eslovenia", "Italia", "Suiza", "Liechtenstein"],
  "Polonia":              ["Alemania", "República Checa", "Eslovaquia", "Ucrania", "Bielorrusia", "Lituania", "Rusia"],
  "Suecia":               ["Noruega", "Finlandia"],
  "Noruega":              ["Suecia", "Finlandia", "Rusia"],
  "Dinamarca":            ["Alemania"],
  "Finlandia":            ["Suecia", "Noruega", "Rusia"],
  "Grecia":               ["Bulgaria", "Macedonia del Norte", "Albania", "Turquía"],
  "Turquía":              ["Grecia", "Bulgaria", "Georgia", "Armenia", "Azerbaiyán", "Irán", "Irak", "Siria"],
  "Rusia":                ["Noruega", "Finlandia", "Estonia", "Letonia", "Lituania", "Polonia", "Bielorrusia", "Ucrania", "Georgia", "Azerbaiyán", "Kazajistán", "Mongolia", "China", "Corea del Norte"],
  "Ucrania":              ["Polonia", "Eslovaquia", "Hungría", "Rumania", "Moldavia", "Rusia", "Bielorrusia"],
  "República Checa":      ["Alemania", "Austria", "Eslovaquia", "Polonia"],
  "Rumania":              ["Ucrania", "Moldavia", "Bulgaria", "Serbia", "Hungría"],
  "Hungría":              ["Austria", "Eslovaquia", "Ucrania", "Rumania", "Serbia", "Croacia", "Eslovenia"],
  "Serbia":               ["Hungría", "Rumania", "Bulgaria", "Macedonia del Norte", "Kosovo", "Montenegro", "Bosnia y Herzegovina", "Croacia"],
  "Croacia":              ["Eslovenia", "Hungría", "Serbia", "Bosnia y Herzegovina", "Montenegro"],
  "Irlanda":              ["Reino Unido"],
  "Bulgaria":             ["Rumania", "Serbia", "Macedonia del Norte", "Grecia", "Turquía"],
  "Eslovaquia":           ["República Checa", "Polonia", "Ucrania", "Hungría", "Austria"],
  "Albania":              ["Montenegro", "Kosovo", "Macedonia del Norte", "Grecia"],
  "Eslovenia":            ["Italia", "Austria", "Hungría", "Croacia"],
  "Lituania":             ["Letonia", "Bielorrusia", "Polonia", "Rusia"],
  "Letonia":              ["Estonia", "Rusia", "Bielorrusia", "Lituania"],
  "Estonia":              ["Letonia", "Rusia"],
  "Macedonia del Norte":  ["Serbia", "Kosovo", "Albania", "Grecia", "Bulgaria"],
  "Bosnia y Herzegovina": ["Croacia", "Serbia", "Montenegro"],
  "Luxemburgo":           ["Francia", "Bélgica", "Alemania"],
  "Malta":                [],
  "Islandia":             [],
  "China":                ["Rusia", "Mongolia", "Kazajistán", "Kirguistán", "Tayikistán", "Afganistán", "Pakistán", "India", "Nepal", "Bután", "Myanmar", "Laos", "Vietnam", "Corea del Norte"],
  "India":                ["Pakistán", "China", "Nepal", "Bután", "Bangladesh", "Myanmar"],
  "Japón":                [],
  "Corea del Sur":        ["Corea del Norte"],
  "Indonesia":            ["Papúa Nueva Guinea", "Timor Oriental", "Malasia"],
  "Tailandia":            ["Myanmar", "Laos", "Camboya", "Malasia"],
  "Vietnam":              ["China", "Laos", "Camboya"],
  "Filipinas":            [],
  "Malasia":              ["Tailandia", "Indonesia", "Brunéi"],
  "Arabia Saudita":       ["Jordania", "Irak", "Kuwait", "Qatar", "Emiratos Árabes Unidos", "Omán", "Yemen"],
  "Irak":                 ["Turquía", "Irán", "Kuwait", "Arabia Saudita", "Jordania", "Siria"],
  "Irán":                 ["Turquía", "Irak", "Kuwait", "Arabia Saudita", "Pakistán", "Afganistán", "Turkmenistán", "Azerbaiyán", "Armenia"],
  "Israel":               ["Líbano", "Siria", "Jordania", "Egipto"],
  "Emiratos Árabes Unidos": ["Arabia Saudita", "Omán", "Qatar"],
  "Pakistán":             ["Irán", "Afganistán", "China", "India"],
  "Bangladesh":           ["India", "Myanmar"],
  "Nepal":                ["China", "India"],
  "Sri Lanka":            [],
  "Singapur":             [],
  "Mongolia":             ["Rusia", "China"],
  "Kazajistán":           ["Rusia", "China", "Kirguistán", "Uzbekistán", "Turkmenistán"],
  "Afganistán":           ["Irán", "Turkmenistán", "Uzbekistán", "Tayikistán", "China", "Pakistán"],
  "Siria":                ["Turquía", "Irak", "Jordania", "Israel", "Líbano"],
  "Yemen":                ["Arabia Saudita", "Omán"],
  "Jordania":             ["Arabia Saudita", "Irak", "Siria", "Israel"],
  "Myanmar":              ["China", "India", "Bangladesh", "Laos", "Tailandia"],
  "Corea del Norte":      ["China", "Rusia", "Corea del Sur"],
  "Camboya":              ["Tailandia", "Laos", "Vietnam"],
  "Uzbekistán":           ["Kazajistán", "Kirguistán", "Tayikistán", "Afganistán", "Turkmenistán"],
  "Azerbaiyán":           ["Rusia", "Georgia", "Armenia", "Irán", "Turquía"],
  "Georgia":              ["Rusia", "Turquía", "Armenia", "Azerbaiyán"],
  "Armenia":              ["Turquía", "Georgia", "Azerbaiyán", "Irán"],
  "Qatar":                ["Arabia Saudita", "Emiratos Árabes Unidos"],
  "Kuwait":               ["Irak", "Arabia Saudita"],
  "Omán":                 ["Emiratos Árabes Unidos", "Arabia Saudita", "Yemen"],
  "Nigeria":              ["Benín", "Níger", "Chad", "Camerún"],
  "Etiopía":              ["Eritrea", "Yibuti", "Somalia", "Kenia", "Sudán del Sur", "Sudán"],
  "Egipto":               ["Libia", "Sudán", "Israel"],
  "Rep. Dem. del Congo":  ["Rep. del Congo", "Angola", "Zambia", "Tanzania", "Burundi", "Ruanda", "Uganda", "Sudán del Sur", "Rep. Centroafricana", "Camerún", "Gabón"],
  "Tanzania":             ["Kenia", "Uganda", "Ruanda", "Burundi", "Rep. Dem. del Congo", "Zambia", "Malaui", "Mozambique"],
  "Kenia":                ["Uganda", "Tanzania", "Etiopía", "Somalia", "Sudán del Sur"],
  "Sudáfrica":            ["Namibia", "Botsuana", "Zimbabue", "Mozambique", "Suazilandia", "Lesoto"],
  "Argelia":              ["Marruecos", "Mauritania", "Malí", "Níger", "Libia", "Túnez"],
  "Marruecos":            ["Argelia", "Mauritania", "España"],
  "Mozambique":           ["Tanzania", "Malaui", "Zambia", "Zimbabue", "Sudáfrica", "Suazilandia"],
  "Ghana":                ["Costa de Marfil", "Burkina Faso", "Togo"],
  "Costa de Marfil":      ["Liberia", "Guinea", "Malí", "Burkina Faso", "Ghana"],
  "Camerún":              ["Nigeria", "Chad", "Rep. Centroafricana", "Rep. Dem. del Congo", "Rep. del Congo", "Gabón", "Guinea Ecuatorial"],
  "Senegal":              ["Mauritania", "Malí", "Guinea", "Guinea-Bisáu", "Gambia"],
  "Zimbabue":             ["Zambia", "Mozambique", "Sudáfrica", "Botsuana"],
  "Túnez":                ["Argelia", "Libia"],
  "Libia":                ["Túnez", "Argelia", "Níger", "Chad", "Sudán", "Egipto"],
  "Somalia":              ["Etiopía", "Kenia", "Yibuti"],
  "Sudán":                ["Egipto", "Libia", "Chad", "Rep. Centroafricana", "Sudán del Sur", "Etiopía", "Eritrea"],
  "Uganda":               ["Sudán del Sur", "Kenia", "Tanzania", "Ruanda", "Rep. Dem. del Congo"],
  "Angola":               ["Rep. Dem. del Congo", "Zambia", "Namibia"],
  "Zambia":               ["Rep. Dem. del Congo", "Tanzania", "Malaui", "Mozambique", "Zimbabue", "Botsuana", "Namibia", "Angola"],
  "Ruanda":               ["Uganda", "Tanzania", "Burundi", "Rep. Dem. del Congo"],
  "Madagascar":           [],
  "Botsuana":             ["Namibia", "Zambia", "Zimbabue", "Sudáfrica"],
  "Namibia":              ["Angola", "Zambia", "Botsuana", "Sudáfrica"],
  "Mauritania":           ["Marruecos", "Argelia", "Malí", "Senegal"],
  "Gabón":                ["Camerún", "Guinea Ecuatorial", "Rep. del Congo"],
  "Australia":            ["Papúa Nueva Guinea"],
  "Nueva Zelanda":        [],
  "Papúa Nueva Guinea":   ["Indonesia", "Australia"],
  "Fiyi":                 [],
  "Vanuatu":              [],
  "Samoa":                [],
  // ── VECINOS FALTANTES ────────────────────────────────────────
  // África continental
  "Burundi":              ["Rep. Dem. del Congo", "Ruanda", "Tanzania"],
  "Benín":                ["Nigeria", "Níger", "Burkina Faso", "Togo"],
  "Burkina Faso":         ["Malí", "Níger", "Benín", "Togo", "Ghana", "Costa de Marfil"],
  "Chad":                 ["Libia", "Sudán", "Rep. Centroafricana", "Níger", "Nigeria", "Camerún"],
  "Eritrea":              ["Sudán", "Etiopía", "Yibuti"],
  "Gambia":               ["Senegal"],
  "Guinea":               ["Guinea-Bisáu", "Senegal", "Malí", "Costa de Marfil", "Sierra Leona", "Liberia"],
  "Guinea-Bisáu":         ["Senegal", "Guinea"],
  "Guinea Ecuatorial":    ["Camerún", "Gabón"],
  "Kosovo":               ["Serbia", "Montenegro", "Albania", "Macedonia del Norte"],
  "Lesoto":               ["Sudáfrica"],
  "Liberia":              ["Guinea", "Sierra Leona", "Costa de Marfil"],
  "Malaui":               ["Tanzania", "Mozambique", "Zambia"],
  "Malí":                 ["Argelia", "Mauritania", "Senegal", "Guinea", "Costa de Marfil", "Burkina Faso", "Níger"],
  "Moldova":              ["Rumania", "Ucrania"],
  "Montenegro":           ["Croacia", "Bosnia y Herzegovina", "Serbia", "Kosovo", "Albania"],
  "Níger":                ["Argelia", "Libia", "Chad", "Nigeria", "Benín", "Burkina Faso", "Malí"],
  "Palestina":            ["Israel", "Jordania", "Egipto"],
  "Rep. Centroafricana":  ["Chad", "Sudán", "Sudán del Sur", "Rep. Dem. del Congo", "Rep. del Congo", "Camerún"],
  "Rep. del Congo":       ["Camerún", "Rep. Centroafricana", "Rep. Dem. del Congo", "Angola", "Gabón", "Guinea Ecuatorial"],
  "Sierra Leona":         ["Guinea", "Liberia"],
  "Sudán del Sur":        ["Sudán", "Etiopía", "Kenia", "Uganda", "Rep. Dem. del Congo", "Rep. Centroafricana"],
  "Suazilandia":          ["Sudáfrica", "Mozambique"],
  "Tayikistán":           ["Afganistán", "China", "Kirguistán", "Uzbekistán"],
  "Togo":                 ["Ghana", "Benín", "Burkina Faso"],
  "Turkmenistán":         ["Kazajistán", "Uzbekistán", "Afganistán", "Irán"],
  "Yibuti":               ["Eritrea", "Etiopía", "Somalia"],
  // Asia continental
  "Bielorrusia":          ["Rusia", "Ucrania", "Polonia", "Lituania", "Letonia"],
  "Brunéi":               ["Malasia"],
  "Bután":                ["China", "India"],
  "Kirguistán":           ["Kazajistán", "Uzbekistán", "Tayikistán", "China"],
  "Laos":                 ["China", "Vietnam", "Camboya", "Tailandia", "Myanmar"],
  "Líbano":               ["Siria", "Israel"],
  "Timor Oriental":       ["Indonesia"],
  // Europa continental
  "Andorra":              ["España", "Francia"],
  "Liechtenstein":        ["Suiza", "Austria"],
  "Mónaco":               ["Francia"],
  "San Marino":           ["Italia"],
  // Islas (sin vecinos terrestres)
  "Antigua y Barbuda":    [],
  "Bahréin":              [],
  "Barbados":             [],
  "Cabo Verde":           [],
  "Chipre":               [],
  "Comoras":              [],
  "Dominica":             [],
  "Granada":              [],
  "Kiribati":             [],
  "Marshall":             [],
  "Mauricio":             [],
  "Maldivas":             [],
  "Micronesia":           [],
  "Nauru":                [],
  "Palaos":               [],
  "Salomón":              [],
  "San Cristóbal y Nieves": [],
  "San Vicente y las Granadinas": [],
  "Santa Lucía":          [],
  "Santo Tomé y Príncipe": [],
  "Seychelles":           [],
  "Tonga":                [],
  "Tuvalu":               [],
};

// ── COORDENADAS (lat, lon) para distancias en GeoWordle ─────────────────
const COORDENADAS = {
  "Afganistán": [33.9, 67.7],
  "Albania": [41.2, 20.2],
  "Alemania": [51.2, 10.5],
  "Andorra": [42.5, 1.5],
  "Angola": [-11.2, 17.9],
  "Antigua y Barbuda": [17.1, -61.8],
  "Arabia Saudita": [24.2, 45.1],
  "Argelia": [28.0, 2.6],
  "Argentina": [-38.4, -63.6],
  "Armenia": [40.1, 45.0],
  "Australia": [-25.3, 133.8],
  "Austria": [47.5, 14.6],
  "Azerbaiyán": [40.1, 47.6],
  "Bahamas": [25.0, -78.0],
  "Bahréin": [26.0, 50.6],
  "Bangladesh": [23.7, 90.4],
  "Barbados": [13.2, -59.5],
  "Belice": [17.2, -88.5],
  "Benín": [9.3, 2.3],
  "Bielorrusia": [53.7, 27.9],
  "Bolivia": [-16.3, -63.6],
  "Bosnia y Herzegovina": [43.9, 17.7],
  "Botsuana": [-22.3, 24.7],
  "Brasil": [-14.2, -51.9],
  "Brunéi": [4.5, 114.7],
  "Bulgaria": [42.7, 25.5],
  "Burkina Faso": [12.4, -1.6],
  "Burundi": [-3.4, 29.9],
  "Bután": [27.5, 90.4],
  "Bélgica": [50.5, 4.5],
  "Cabo Verde": [16.0, -24.0],
  "Camboya": [12.6, 104.9],
  "Camerún": [3.8, 11.5],
  "Canadá": [56.1, -106.3],
  "Chad": [15.5, 18.7],
  "Chile": [-35.7, -71.5],
  "China": [35.9, 104.2],
  "Chipre": [35.1, 33.4],
  "Colombia": [4.6, -74.1],
  "Comoras": [-11.7, 43.3],
  "Corea del Norte": [40.3, 127.5],
  "Corea del Sur": [35.9, 127.8],
  "Costa Rica": [9.7, -83.8],
  "Costa de Marfil": [7.5, -5.6],
  "Croacia": [45.1, 16.4],
  "Cuba": [21.5, -79.5],
  "Dinamarca": [56.3, 9.5],
  "Dominica": [15.4, -61.4],
  "Ecuador": [-1.8, -78.2],
  "Egipto": [26.8, 30.8],
  "El Salvador": [13.8, -88.9],
  "Emiratos Árabes Unidos": [23.4, 53.8],
  "Eritrea": [15.2, 39.8],
  "Eslovaquia": [48.7, 19.7],
  "Eslovenia": [46.1, 14.8],
  "España": [40.5, -3.7],
  "Estados Unidos": [37.1, -95.7],
  "Estonia": [58.6, 25.0],
  "Etiopía": [9.1, 40.5],
  "Filipinas": [12.9, 121.8],
  "Finlandia": [61.9, 25.7],
  "Fiyi": [-17.7, 178.1],
  "Francia": [46.2, 2.2],
  "Gabón": [-0.8, 11.6],
  "Gambia": [13.4, -15.3],
  "Georgia": [42.3, 43.4],
  "Ghana": [7.9, -1.0],
  "Granada": [12.1, -61.7],
  "Grecia": [39.1, 21.8],
  "Guatemala": [15.8, -90.2],
  "Guinea": [11.0, -10.9],
  "Guinea Ecuatorial": [1.7, 10.3],
  "Guinea-Bisáu": [11.8, -15.2],
  "Guyana": [4.9, -58.9],
  "Haití": [19.0, -72.3],
  "Honduras": [15.0, -86.5],
  "Hungría": [47.2, 19.5],
  "India": [20.6, 79.0],
  "Indonesia": [-0.8, 113.9],
  "Irak": [33.2, 43.7],
  "Irlanda": [53.4, -8.2],
  "Irán": [32.4, 53.7],
  "Islandia": [64.9, -18.5],
  "Israel": [31.0, 34.9],
  "Italia": [42.8, 12.8],
  "Jamaica": [18.1, -77.3],
  "Japón": [36.2, 138.3],
  "Jordania": [31.2, 36.5],
  "Kazajistán": [48.0, 66.9],
  "Kenia": [-0.2, 37.9],
  "Kirguistán": [41.2, 74.8],
  "Kiribati": [1.9, -157.4],
  "Kosovo": [42.6, 21.0],
  "Kuwait": [29.3, 47.5],
  "Laos": [17.4, 103.0],
  "Lesoto": [-29.6, 28.2],
  "Letonia": [56.9, 24.6],
  "Liberia": [6.4, -9.4],
  "Libia": [26.3, 17.2],
  "Liechtenstein": [47.2, 9.5],
  "Lituania": [55.2, 23.9],
  "Luxemburgo": [49.8, 6.1],
  "Líbano": [33.9, 35.5],
  "Macedonia del Norte": [41.6, 21.7],
  "Madagascar": [-18.8, 46.9],
  "Malasia": [2.5, 112.5],
  "Malaui": [-13.3, 34.3],
  "Maldivas": [3.2, 73.2],
  "Malta": [35.9, 14.4],
  "Malí": [17.6, -4.0],
  "Marruecos": [31.8, -7.1],
  "Marshall": [7.1, 171.2],
  "Mauricio": [-20.3, 57.6],
  "Mauritania": [21.0, -10.9],
  "Micronesia": [6.9, 158.2],
  "Moldova": [47.4, 28.4],
  "Mongolia": [46.9, 103.8],
  "Montenegro": [42.7, 19.4],
  "Mozambique": [-18.7, 35.5],
  "Myanmar": [17.1, 96.0],
  "México": [23.6, -102.5],
  "Mónaco": [43.7, 7.4],
  "Namibia": [-22.0, 17.1],
  "Nauru": [-0.5, 166.9],
  "Nepal": [28.4, 84.1],
  "Nicaragua": [12.9, -85.2],
  "Nigeria": [9.1, 8.7],
  "Noruega": [60.5, 8.5],
  "Nueva Zelanda": [-40.9, 174.9],
  "Níger": [17.6, 8.1],
  "Omán": [21.5, 55.9],
  "Pakistán": [30.4, 69.3],
  "Palaos": [7.5, 134.6],
  "Palestina": [31.9, 35.2],
  "Panamá": [8.5, -80.8],
  "Papúa Nueva Guinea": [-6.3, 143.9],
  "Paraguay": [-23.4, -58.4],
  "Países Bajos": [52.1, 5.3],
  "Perú": [-9.2, -75.0],
  "Polonia": [51.9, 19.1],
  "Portugal": [39.4, -8.2],
  "Qatar": [25.4, 51.2],
  "Reino Unido": [55.4, -3.4],
  "Rep. Centroafricana": [6.6, 20.9],
  "Rep. Dem. del Congo": [-4.0, 21.8],
  "Rep. del Congo": [-0.2, 15.8],
  "República Checa": [49.8, 15.5],
  "República Dominicana": [18.7, -70.2],
  "Ruanda": [-1.9, 29.9],
  "Rumania": [45.9, 24.9],
  "Rusia": [61.5, 105.3],
  "Salomón": [-9.6, 160.2],
  "Samoa": [-13.8, -172.1],
  "San Cristóbal y Nieves": [17.3, -62.7],
  "San Marino": [43.9, 12.5],
  "San Vicente y las Granadinas": [13.3, -61.2],
  "Santa Lucía": [13.9, -60.9],
  "Santo Tomé y Príncipe": [0.2, 6.6],
  "Senegal": [14.5, -14.5],
  "Serbia": [44.0, 21.0],
  "Seychelles": [-4.7, 55.5],
  "Sierra Leona": [8.5, -11.8],
  "Singapur": [1.4, 103.8],
  "Siria": [34.8, 38.9],
  "Somalia": [5.2, 46.2],
  "Sri Lanka": [7.9, 80.8],
  "Suazilandia": [-26.5, 31.5],
  "Sudáfrica": [-29.0, 25.1],
  "Sudán": [12.9, 30.2],
  "Sudán del Sur": [6.9, 31.3],
  "Suecia": [60.1, 18.6],
  "Suiza": [46.8, 8.2],
  "Surinam": [3.9, -56.0],
  "Tailandia": [15.9, 100.9],
  "Tanzania": [-6.4, 34.9],
  "Tayikistán": [38.9, 71.3],
  "Timor Oriental": [-8.9, 125.7],
  "Togo": [8.6, 0.8],
  "Tonga": [-21.2, -175.2],
  "Trinidad y Tobago": [10.7, -61.2],
  "Turkmenistán": [38.9, 59.6],
  "Turquía": [38.9, 35.2],
  "Tuvalu": [-8.5, 179.2],
  "Túnez": [33.9, 9.6],
  "Ucrania": [48.4, 31.2],
  "Uganda": [1.4, 32.3],
  "Uruguay": [-32.5, -55.8],
  "Uzbekistán": [41.4, 64.6],
  "Vanuatu": [-15.4, 166.9],
  "Venezuela": [6.4, -66.6],
  "Vietnam": [14.1, 108.3],
  "Yemen": [15.6, 48.5],
  "Yibuti": [11.8, 42.6],
  "Zambia": [-13.1, 27.8],
  "Zimbabue": [-20.0, 30.1],
};

// ── REGIONES ─────────────────────────────────────────────────
const REGIONES = {
  'mundo':        { label: 'Todo el mundo',      emoji: '🌍' },
  'america_norte':{ label: 'América del Norte',  emoji: '🌎' },
  'america_sur':  { label: 'América del Sur',    emoji: '🌎' },
  'europa':       { label: 'Europa',             emoji: '🌍' },
  'asia':         { label: 'Asia',               emoji: '🌏' },
  'africa':       { label: 'África',             emoji: '🌍' },
  'oceania':      { label: 'Oceanía',            emoji: '🌏' },
};

// ── MODOS ────────────────────────────────────────────────────
const MODOS = {
  'banderas':   { label: 'Banderas',   emoji: '🏳️', descripcion: 'Identifica el país por su bandera' },
  'capitales':  { label: 'Capitales',  emoji: '🏙️', descripcion: 'Encuentra la capital del país' },
  'poblacion':  { label: 'Población',  emoji: '👥', descripcion: '¿Qué país tiene más habitantes?' },
  'banderas_inverso': { label: 'Banderas Inverso', emoji: '🔄🏳️', descripcion: 'Identifica la bandera por el nombre del país' },
};

// ── HELPERS ──────────────────────────────────────────────────

/** Devuelve los países filtrados por región. */
function getPaisesPorRegion(region) {
  if (region === 'mundo') return [...PAISES];
  return PAISES.filter(p => p.region === region);
}

/** Devuelve n elementos aleatorios del array (sin repetición). */
function muestraAleatoria(arr, n) {
  const copia = [...arr];
  for (let i = copia.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copia[i], copia[j]] = [copia[j], copia[i]];
  }
  return copia.slice(0, n);
}

/** Mezcla un array in-place (Fisher-Yates). */
function mezclar(arr) {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

/** Formatea una cifra de población de forma legible. */
function formatPoblacion(n) {
  if (n >= 1_000_000_000) return (n / 1_000_000_000).toFixed(1) + 'B';
  if (n >= 1_000_000)     return (n / 1_000_000).toFixed(1) + 'M';
  if (n >= 1_000)         return (n / 1_000).toFixed(0) + 'K';
  return n.toString();
}

// ── CURIOSIDADES ─────────────────────────────────────────────
const CURIOSIDADES = [
  "Rusia es tan grande que abarca 11 zonas horarias distintas.",
  "Canadá tiene más lagos que el resto del mundo combinado.",
  "La Ciudad del Vaticano es el país más pequeño del mundo, cabría 8 veces en el Central Park de Nueva York.",
  "Australia es más ancha que la luna.",
  "En Filipinas hay más de 7.600 islas.",
  "Indonesia tiene la mayor población musulmana del mundo.",
  "El Monte Everest crece unos 4 milímetros cada año.",
  "Francia es el país que abarca más zonas horarias en el mundo (12), gracias a sus territorios de ultramar.",
  "Japón sufre alrededor de 1.500 terremotos al año.",
  "Hay un pueblo en Noruega llamado 'Å'. Es el nombre de lugar más corto del mundo.",
  "Islandia no tiene ejército ni fuerza aérea, y la policía no suele portar armas.",
  "Papúa Nueva Guinea es el país con mayor diversidad lingüística del mundo, con más de 820 lenguas vivas.",
  "Groenlandia es la isla más grande del mundo, pero no es un continente.",
  "La frontera terrestre más larga de Francia es con... ¡Brasil! (debido a la Guayana Francesa).",
  "El 90% de la población mundial vive en el hemisferio norte."
];
